// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type EmailCodeReply struct {
	Code string `json:"code"`
}

type EmailCodeRequest struct {
	Email string `json:"email"`
}

type LoginReply struct {
	Token string `json:"token"`
}

type LoginRequest struct {
	Name     string `json:"name" `
	Password string `json:"password"`
}

type UserDetailReply struct {
	Name  string `json:"name" `
	Email string `json:"email"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserRegisterReply struct {
	Name     string `json:"Name"`
	Password string `json:"password"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}
